name: AbilityPvP
version: '1.2-SNAPSHOT'
main: org.vicson.abilitypvp.abilitypvp
api-version: '1.21.1'
commands:
  help:
    description: "help me"
  good:
    description: "good"
  ability:
    description: "choose ability"
  abilitycancel:
    description: "clear ability"
  abilityreload:
    description: "reload ability config"
    permission: abilitypvp.reload
permissions:
  abilitypvp.reload:
    description: "Allows reloading AbilityPvP config"
    default: op
